name: Build, Push & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_PHP: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-php
  IMAGE_NGINX: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-nginx
  COMPOSE_FILE_PATH: docker-compose.registry.yml

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push PHP
        uses: docker/build-push-action@v6
        with:
          context: .
          file: php.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PHP }}:latest
            ${{ env.IMAGE_PHP }}:${{ github.sha }}

      - name: Build & Push Nginx
        uses: docker/build-push-action@v6
        with:
          context: .
          file: nginx.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NGINX }}:latest
            ${{ env.IMAGE_NGINX }}:${{ github.sha }}

      - name: Update compose file to use latest tags (optional)
        run: |
          sed -i 's#image: .*/webapp-php:.*#image: '"${{ env.IMAGE_PHP }}:latest"'#' ${{ env.COMPOSE_FILE_PATH }}
          sed -i 's#image: .*/webapp-nginx:.*#image: '"${{ env.IMAGE_NGINX }}:latest"'#' ${{ env.COMPOSE_FILE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Compose)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ""                           # lämna tomt vid compose
          configuration-file: ${{ env.COMPOSE_FILE_PATH }}
