name: Build, Push & Deploy (WebApp Docker)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_PHP: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-php
  IMAGE_NGINX: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-nginx
  COMPOSE_TEMPLATE: docker-compose.registry.yml
  DEPLOY_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # 🔐 Login explicit mot Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # ex: dogman11
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Docker Hub RW-token

      # ✅ Snabb koll att auth funkar och basbilder kan hämtas
      - name: Sanity: pull base images
        run: |
          docker pull docker.io/library/php:8.2-fpm-alpine
          docker pull docker.io/library/nginx:1.25-alpine

      - name: Build & push PHP image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: php.Dockerfile
          pull: true
          push: true
          tags: |
            ${{ env.IMAGE_PHP }}:latest
            ${{ env.IMAGE_PHP }}:${{ env.DEPLOY_TAG }}

      - name: Build & push Nginx image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: nginx.Dockerfile
          pull: true
          push: true
          tags: |
            ${{ env.IMAGE_NGINX }}:latest
            ${{ env.IMAGE_NGINX }}:${{ env.DEPLOY_TAG }}

      - name: Render compose with commit tag
        run: |
          cp "${{ env.COMPOSE_TEMPLATE }}" azure.compose.rendered.yml
          sed -i -E "s#image: .*/webapp-php:.*#image: ${{ env.IMAGE_PHP }}:${{ env.DEPLOY_TAG }}#g" azure.compose.rendered.yml
          sed -i -E "s#image: .*/webapp-nginx:.*#image: ${{ env.IMAGE_NGINX }}:${{ env.DEPLOY_TAG }}#g" azure.compose.rendered.yml
          echo "----- RENDERED COMPOSE -----"
          cat azure.compose.rendered.yml

      - uses: actions/upload-artifact@v4
        with:
          name: azure-compose
          path: azure.compose.rendered.yml

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: azure-compose

      - name: Azure Login (new method)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App (Compose)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ""
          configuration-file: azure.compose.rendered.yml
